### ISSUE TITLE
Odometry: Rotation should be applied to base footprint (or support link?) 

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_motion#112]
Currently, the rotation of the IMU (pitch and roll) is applied to the base link. This results in the robot rotating around its center in the odom frame instead of oscillating from left to right (also translating the base_link and keeping the base_footprint or support link fixed in translation).

**Comment by SammyRamone** [comment]
yes thats correct. we will use the center of pressure to comopute the correct rotation point
