### ISSUE TITLE
Odometry during stand up is wrong

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_motion#129]
## Expected behavior
During the stand up, the odometry should still be correct.

## Current behavior
The odometry is wrong, the robot seems to be in the ground.

## Possible Solution
This might be due to the odometry fuser that selects the roll and pitch of the IMU and the yaw of the walking which might be wrong when the robot is lying.

![odometry_during_stand_up](https://user-images.githubusercontent.com/25013222/73951677-2baef200-48fe-11ea-997b-b0ebb8f044d4.gif)

**Comment by Flova** [comment]
The weird rotation is due to the gimbal lock at 90° Pitch. This can be fixed by using a quaternion for the merging process, instead of the RPY coordinates.

**Comment by Flova** [comment]
I think this would be helpfull, to determin the Rotation around the Z Axis.

**Comment by Flova** [comment]
Closed in #132
