### ISSUE TITLE
HCM: wrong state during stand up

### ISSUE THREAD

**Issue by SammyRamone** [bit-bots/bitbots_motion#131]
## Expected behavior
HCM should publish "GettingUp" when standing up

## Current behavior
I publishes "AnimationRunning"

## Steps to Reproduce
Start motion_standalone. Let robot fall and stand up again.

**Comment by NFiedler** [comment]
Is this actually a problem? Because we check whether an animation is played and as long as we stand up with an animation, this is true.

**Comment by timonegk** [comment]
Nevertheless the state `GettingUp` is more tight than `AnimationRunning`. Therefore it should be published instead.

**Comment by SammyRamone** [comment]
fixed in https://github.com/bit-bots/bitbots_motion/pull/154
