### ISSUE TITLE
Odometry drifts in z axis

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_motion#162]
## Expected behavior
When visualizing the robot's walking in rviz, the robot should stay on the ground plane.

## Current behavior
Instead, the robot's z coordinate slowly increases while walking until the robot flies in the sky.

## Steps to Reproduce
1. `roslaunch bitbots_body_behavior rviz_behavior_test.launch`
2. In rviz, select a navigation goal and look at the robot going upwards.

## Context (Environment)
- [x] RViz
- [ ] Simulator
- [ ] Robot
- [ ] Local

## Possible Solution
The problem was introduced in #158, since then, the odometry fuser uses the z values of the walking which seem to be a bit off. Maybe we should remove the z walking feature since it is not really needed or at least remove it from the odometry fuser for now.

**Comment by SammyRamone** [comment]
sounds reasonable to me. The z movement feature is not really needed, it also introduced unnecessary code complexity, therefore I'm pro removing it again
