### ISSUE TITLE
Use different dynup actions in HCM

### ISSUE THREAD

**Issue by Flova** [bit-bots/bitbots_motion#186]
Split dynup into different actions to prevent playing walkready when the robot falls during standup.

The first action consits of the part from the floor to the sitting position. It is executed without checking for falls.
Afterwards a common standup part for both the front and the back standup is executed. The fallchecker is active in this part and aborts if the robot falls.

**Comment by 16stelter** [comment]
Afaik, this is already integrated. Closing this issue for now.
