### ISSUE TITLE
Invalid Quaternions published py odometry fuser

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_motion#224]
## Current behavior
The odometry fuser publishes quaternions (0, 0, 0, 0.5). Everyone else complains that they are not normalized.
The issue was introduced in #223.

## Steps to Reproduce
1. `roslaunch bitbots_bringup simulator_teamplayer.launch`

**Comment by SammyRamone** [comment]
Sorry, I only checked the motion odometry and forgot to test the fuser. I pushed a PR with a fix
