### ISSUE TITLE
Standing up from back often doesn't work

### ISSUE THREAD

**Issue by johagge** [bit-bots/bitbots_motion#280]
It often takes several tries to get up after having fallen on our back.

## Expected behavior

Getting up without falling over to our back several times
## Current behavior

https://user-images.githubusercontent.com/31103663/122266436-15457d00-ceda-11eb-807f-dcdf5cae3b5e.mp4

## Steps to Reproduce

1. Fall to the back
2. Try to get up
3. See how (most of the time) it takes a while
...

## Context (Environment)

- [ ] RViz
- [X] Simulator
- [ ] Robot
- [ ] Local

## Possible Solution

 A quick fix would probably be to fall to the front in our getting up animation as that one seems to be more stable.

**Comment by 16stelter** [comment]
This should be fixed by now, as long as a good parameter set is chosen.
