### ISSUE TITLE
First request to dynup from hcm is not working

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_motion#371]
## Expected behavior
The robot should go to walkready when the simulator starts.

## Current behavior
The robot is stuck in state 5 (STARTUP) and no request from the HCM reaches dynup.

## Steps to Reproduce
`ros2 launch bitbots_bringup simulator.launch`

## Context (Environment)
- [ ] RViz
- [x] Simulator
- [ ] Robot
- [ ] Local

**Comment by jaagut** [comment]
@timonegk @Flova isn't this fixed now?

**Comment by Flova** [comment]
I think it successfully goes into walkready after the simulation started. So this is fixed.
