### ISSUE TITLE
refactor spline engine and stabilizer

### ISSUE THREAD

**Issue by SammyRamone** [bit-bots/bitbots_motion#50]
we decided that we want to refactor our splines in a way that we have an abstract spline engine to get a common interface and to have utility functions (like debug markers for all splines) in one place.
related to this is also small refactoring of the spline classes (e.g. adding debug marker methods).
The stabilizer will also be an abstract class. Implementation will maybe be based on existing libraries (e.g. ros controllers).
The engine and stabilizer should than be used in QuinticWalk, DynamicKick and DynUp

**Comment by SammyRamone** [comment]
as a library for controller, the base library which is also used in ros control would be a simple candidate https://github.com/ros-controls/control_toolbox

**Comment by ftsell** [comment]
@timonegk can you upload the notes we took when we discussed this?

**Comment by ftsell** [comment]
I've received them from Timon: [splines.txt](https://github.com/bit-bots/bitbots_motion/files/3590487/splines.txt)

**Comment by ftsell** [comment]
I've also recently stumbled upon [Behavior Driven Development](https://cucumber.io/docs/bdd/) and would like to try it out. I think the implementation corresponding to this issue might be a good trial.

**Comment by timonegk** [comment]
This was closed in #63, #64 and #89.
