### ISSUE TITLE
quintic_walk, dynamic_kick: new message for foot sensors

### ISSUE THREAD

**Issue by jgueldenstein** [bit-bots/bitbots_motion#66]
https://github.com/bit-bots/bitbots_msgs/pull/4 changes the foot pressure message, this has to be adapted in the dynamic kick (pid controll torso position) and quintic walk (phase reset)

**Comment by timonegk** [comment]
The dynamic kick is not affected and the walking has been adapter in f16ba6890357bebdf6f9870597d2109a03e58d9b.
