### ISSUE TITLE
animation walkready is not always exactly reached

### ISSUE THREAD

**Issue by ftsell** [bit-bots/bitbots_motion#85]
This is a bug appearing to be in the animation server and affecting hcm.

It's manifestation is a robot which is in the walkready position but keeps twitching. In this case hcm is stuck in the playing walkready state.

My educated guess is that the Robot does not reach the _exact_ walkready position for some reason causing the animation server to not finish the _play amimation_ action in turn causing the hcm to be stuck.

My proposed resolution is to have an allowed error margin in the animation server. Inside that margin an animation would be considered _completed_ (but maybe only after a timeout).

**Comment by SammyRamone** [comment]
did you do it on the robot or in simulation?
the animation server plays the animation open loop, so its not possible that it gets stuck there.
The HCM has an error margin, which may needs to be increased, especially for simulation, since the knees seem to bend more there

**Comment by ftsell** [comment]
I reported this error while @NFiedler was working on the robot.

If the AnimationServer works open loop, that is indeed probably not the problem.

But I believe we had this error in Sydney at some point as well. @timonegk or @SammyRamone don't you remember?

**Comment by SammyRamone** [comment]
I don't remember if there was a problem in sydney with it. If the bug is still present, we can just increase the error margin in the HCM config. otherwise we can close the issue

**Comment by timonegk** [comment]
The problem persists and increasing the error margin is not sufficient because the robot is not stable in the reached position. The problem might be that the motors (especially the ankle pitches) do not reach their target positions.

**Comment by SammyRamone** [comment]
> The problem persists and increasing the error margin is not sufficient because the robot is not stable in the reached position. The problem might be that the motors (especially the ankle pitches) do not reach their target positions.

but why does increasing the error margin does not help? it is specially for this case, where the actual position of the robot differs from the animation file

**Comment by timonegk** [comment]
Maybe the walkready animation is restarted before the previous execution is finished.

**Comment by SammyRamone** [comment]
does not happen anymore on new robot version
