### ISSUE TITLE
HCM: Walkready between falling and fallen

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_motion#96]
The HCM plays walkready between the falling and fallen animations because the fallen detection takes some time that the robot is lying around. In this short period of time, the robot is neither falling nor fallen and therefore the HCM plays the walkready animation. A possible fix would be to add a pause in the animation definition or in the HCM falling sequence. I would prefer the latter because it would allow to document the reasons for the pause and it would persist a regeneration of the animation. What do you think @ftsell @SammyRamone?
The preferable solution would of course be to make the fallen detection detect the state immediately. But as far as I know, that is not possible (@Flova)?

**Comment by timonegk** [comment]
This was actually due to an error in the DSD.

**Comment by timonegk** [comment]
I talked to @Flova: The fallen detection detects the fallen state theoretically immediately, but the problem is that the robot bounces off the ground. When it bounces, the falling detection is not triggered because the robot is being lifted and is not falling and the fallen detection is not triggered because the robot is still moving.

**Comment by SammyRamone** [comment]
maybe introduce additional boolean term in falling detection, which disables it if current orientation is too close to lying on the ground (roll or pitch almost 90°)
